# Generated by Django 3.0.6 on 2020-05-12 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Influencer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=256, unique=True)),
                ('name', models.CharField(max_length=256)),
                ('url_profile_picture', models.URLField(max_length=512)),
                ('bio', models.CharField(max_length=514)),
                ('followers', models.IntegerField()),
                ('posts', models.IntegerField()),
                ('engagement', models.FloatField()),
                ('category', models.CharField(max_length=256)),
            ],
        ),
    ]
