# Generated by Django 3.0.5 on 2020-09-06 00:28

from django.db import migrations, models
import djongo.models.fields
import influencers.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InstagramPost',
            fields=[
                ('id', models.CharField(max_length=256, primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=256)),
                ('shortcode', models.CharField(max_length=256)),
                ('comment_count', models.IntegerField()),
                ('likes_count', models.IntegerField()),
                ('user_id', models.CharField(max_length=256)),
                ('username', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='InstagramUser',
            fields=[
                ('id', models.CharField(max_length=256, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=256)),
                ('fullname', models.CharField(max_length=256)),
                ('bio', models.CharField(blank=True, max_length=514)),
                ('has_channel', models.BooleanField(null=True)),
                ('is_business_account', models.BooleanField(null=True)),
                ('business_category_name', models.CharField(max_length=256, null=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('profile_pic_url', models.URLField(blank=True, max_length=512)),
                ('user_status', djongo.models.fields.ArrayField(model_container=influencers.models.InstagramUserStatus, model_form_class=influencers.models.InstagramUserStatusForm, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tweet',
            fields=[
                ('id_str', models.CharField(max_length=256, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField()),
                ('text', models.CharField(max_length=1024)),
                ('user_id', models.CharField(max_length=256)),
                ('in_reply_to_status_id_str', models.CharField(max_length=256, null=True)),
                ('in_reply_to_user_id_str', models.CharField(max_length=256, null=True)),
                ('in_reply_to_screen_name', models.CharField(max_length=256, null=True)),
                ('type', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='TwitterUser',
            fields=[
                ('id_str', models.CharField(max_length=256, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256)),
                ('screen_name', models.CharField(max_length=256)),
                ('location', models.CharField(max_length=256, null=True)),
                ('url', models.URLField(max_length=512, null=True)),
                ('description', models.CharField(max_length=1024, null=True)),
                ('verified', models.BooleanField(default=False)),
                ('profile_image_url', models.URLField(max_length=512, null=True)),
                ('lang', models.CharField(max_length=256, null=True)),
                ('user_status', djongo.models.fields.ArrayField(model_container=influencers.models.TwitterUserStatus, model_form_class=influencers.models.TwitterUserStatusForm, null=True)),
            ],
        ),
    ]
